### PR TITLE
Add support for Buildkite

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This PR adds support for Buildkite as a CI source, including tests.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
I think the tests should be passing, but it looks like AppVeyor cannot connect to github.com (SSL error).

**Comment by jacobwgillespie** [comment]
Thanks, happy to contribute!  🚀

**Comment by orta** [comment]
Awesome - thanks @jacobwgillespie 

also, I've invited you to the org, as a part of [Moya Community Continuity](https://github.com/Moya/contributors/issues/6) - you're welcome to participate (or not) in PRs and help out at a level that works for you.

**Comment by jacobwgillespie** [comment]
Awesome!  Thanks 🎉

**Pull request merged**
