### PR TITLE
Move dtslint to devDependencies

### LINKED ISSUE #319: dtslint shouldn’t be in runtime dependencies
Because it depends on tsutils which requires a TypeScript peer dependency:

> npm WARN tsutils@1.9.1 requires a peer of typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev but none was installed.

### PR DESCRIPTION
**Pull request by sapegin**
Fixes #319

### CODE REVIEW

**Comment by orta** [comment]
Hrm interesting, maybe I should add this at runtime on the CI test instead

**Comment by orta** [comment]
interesting, the code already does `- if [[ $TRAVIS_NODE_VERSION == "8" ]]; then yarn add dtslint; yarn dts-lint; fi`

**Comment by sapegin** [comment]
So we can just remove from package.json?

**Comment by orta** [comment]
That's what I'm trying in #323 - but now basically every PR is red, something must have changed on travis side.

**Comment by orta** [comment]
Fixed in #323 - thanks!

**Pull request closed without merging**
