### PR TITLE
Support danger pr also on BitBucket server

### PR DESCRIPTION
**Pull request by f-meloni**
First PR on Danger-js and first time i write something with js :D

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this looks good - just a changelog entry should be fine - did you verify this works?

**Comment by f-meloni** [comment]
Looks working, but to be 100% sure i will try it tomorrow morning

**Comment by f-meloni** [comment]
I actually manage to check it now, is working 🎉

**Comment by orta** [comment]
Cool beans, merge on green

**Review by Brayan-724 — COMMENTED** [review]
Good

**Pull request merged**
