### PR TITLE
add options 'newComment' and 'removePreviousComments'

### LINKED ISSUE #547: [BitBucketServer] Always updates the comment
Seems like the danger is always updating the one comment in the PR instead of deleting it and adding another.
When it is just updated, it is easy to miss.

### PR DESCRIPTION
**Pull request by davidhouweling**
This PR adds options `newComment` and `removePreviousComments`.

This is [very loosely] based on the options available in the [Ruby implementation](https://github.com/danger/danger/blob/108e82ab793cc48a2756b9881a94e01cce57d353/lib/danger/commands/runner.rb#L67-L68).

This PR resolves #547.

Note to reviewers, would be good to sanity check that this the implementation is as expected as I simply did the code change purely based on what I thought the description of the options implied.

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  
<b>🃏 FAIL</b> in <a href="https://github.com/davidhouweling/danger-js/blob/feat/547-delete-new-comment/source/runner/_tests/_executor.test.ts">_executor.test.ts</a>


<li>
<a href='https://github.com/davidhouweling/danger-js/blob/feat/547-delete-new-comment/source/runner/_tests/_executor.test.ts#L364'>Deletes all old inline comments when 'removePreviousComments' option has been specified</a>
<br/>
Expected mock function to have been called three times, but it was called six times.

<details>
<summary>Full message</summary>
<pre><code>
Error: expect(jest.fn()).toHaveBeenCalledTimes(3)

Expected mock function to have been called three times, but it was called six times.
    at Object.<anonymous> (/home/travis/build/danger/danger-js/source/runner/_tests/_executor.test.ts:364:42)
    at step (/home/travis/build/danger/danger-js/source/runner/_tests/_executor.test.ts:43:23)
    at Object.next (/home/travis/build/danger/danger-js/source/runner/_tests/_executor.test.ts:24:53)
    at fulfilled (/home/travis/build/danger/danger-js/source/runner/_tests/_executor.test.ts:15:58)
</code></pre>
</details>
</li>
<br/>


  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a changelog entry for your changes. You can find it in `CHANGELOG.md` 

Please add your change and name to the master section.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9e5679cc5021b589e792fcafad404f473a19a220
</p>

**Comment by orta** [comment]
I will give this a second look later, but as far as I remember  - this works like I'd expect from the ruby implementation and I'm on-board with the changes 👍🏻 

Nice one

**Comment by orta** [comment]
Thanks for your patience, yeah, this acts similar to how the ruby version works to me 👍🏻

**Comment by orta** [comment]
Shipped in 10.6.0

**Pull request merged**
