### PR TITLE
Fix nulls in created_files

### PR DESCRIPTION
**Pull request by keith**
https://github.com/danger/danger-js/issues/807

### CODE REVIEW

**Comment by keith** [comment]
Testing this locally now shows `/dev/null` as the file instead of a null path. But maybe it should actually be showing the new file path?

**Comment by fbartho** [comment]
@keith I think I agree that the canonical path should *always* be the "final path" except for "deleted files".

**Comment by keith** [comment]
Yea you're right, I'm not sure why the `to` is null here then, I wonder if this is an issue on the `parse-diff` side

**Comment by keith** [comment]
The object I get back for these files from parse-diff is:

```
  { chunks: [],
    deletions: 0,
    additions: 0,
    from: '/dev/null',
    to: undefined,
    new: true,
    index: [ '0000000000..b4aca5d807' ] },
```

So that's interesting.

**Comment by orta** [comment]
Does that make it deleted?

**Pull request closed without merging**
