### PR TITLE
Support for Nevercode.io

### PR DESCRIPTION
**Pull request by fbartho**
I'm trying out [Nevercode.io](Nevercode.io) as an option for our CI provider now that BuddyBuild is shutting down their Android product, and we use TypeScript and danger-js in our pipeline.

This is an attempt to write a CISource for Nevercode.

- [Nevercode Environment Variable Official Docs](https://developer.nevercode.io/v1.0/docs/environment-variables-files)

This is my first time working in this repo, so please do let me know how I can improve this PR.

Thanks!

### CODE REVIEW

**Comment by fbartho** [comment]
Note: I'm not 100% certain this will work yet, I'm getting issue #407 -- and the turn around time for testing changes to danger on my custom branch is really slow in a CI environment.

**Comment by orta** [comment]
This looks exactly like I'd expect 👍

**Comment by orta** [comment]
Re-ran the failed build, it was a 404 on a dep

**Comment by orta** [comment]
I'd rather get this in then iterate

**Pull request merged**
