### PR TITLE
Prevent GitHub adding a <p> tag to <td> inside issue comment.

### PR DESCRIPTION
**Pull request by patrickkempff**
Thanks for this awesome project. It looks awesome! There was one thing that caught my attention; the vertical alignment of content in the table seemed somewhat off. 

Before:
screen shot 2018-11-05 at 12 44 58

After:
screen shot 2018-11-05 at 12 43 59

This PR fixes that.

After comparing the implementation and the code that GitHub renders. I found that the GitHub markdown implementation adds an <p> tag inside the <td> when it thinks the text should be a text block (because of the linebreak before and after `${message}`). When it appends a `<p>` the user-agent add the default margin at the bottom of the paragraph. (as an example; chrome adds margin-bottom: 16px;) This messes up the vertical alignment.

I removed the linebreaks and github andeverything seems to render everything correctly.

HTML output by github:

Before:
screen shot 2018-11-05 at 13 01 01

After:
screen shot 2018-11-05 at 13 03 22

**Important:** I also updated the `githubIssueTemplates.test.ts.snap` snapshot reflect the changes.

PS. @orta I am sure this is not the right way but I wanted to thank you and the artsy crew for the inspiring talks @facebookHQ in london last July.

### CODE REVIEW

**Comment by orta** [comment]
Hrm, part of me feels like this is intentional (otherwise why would it be so weird?) - let's give it a shot anyway, and see what happens.

**Comment by patrickkempff** [comment]
> Hrm, part of me feels like this is intentional (otherwise why would it be so weird?) - let's give it a shot anyway, and see what happens.

After some searching around I found an commit from 2 years ago by @macklinu.
This discussion seems to be related: https://github.com/danger/danger-js/issues/240#issuecomment-299481579. I am not sure if it is still relevant

**Comment by orta** [comment]
It probably is, I wonder if maybe we will need to do multi-line detection or something like that to make sure it handles inline html

**Comment by patrickkempff** [comment]
@orta maybe we should revert this PR until we have a better solution handling both cases. What do you think?

**Comment by orta** [comment]
It's not shipped yet, so maybe we can look to see if the string includes a few particular chars and just include that?

**Pull request merged**
