### PR TITLE
feat(template): support timestamp via env. variable

### PR DESCRIPTION
**Pull request by kwonoj**
This PR adds additional check for environment variable `DANGER_TIMESTAMP`, to log date of time dangerfile posted latest update.

### CODE REVIEW

**Comment by orta** [comment]
A pattern I found in Danger-rb was to just throw arbitrary data like this inside the table's HTML:

screen shot 2017-01-15 at 11 30 06 am

I'd have no problem with timestamps being on the table all the time e.g: `<table data-danger-timestamp="1980-12-23Z233..."/>`

This means less options, and that data is always there. How does that sound?

**Comment by kwonoj** [comment]
hmm, my intention was actually emit timestamp, instead of having it as arbitrary data.

We sometimes had cases like code author frequently update commit and wasn't sure if danger validation is up to date / or sometimes danger run silently fails (like module installation fail before running danger) so danger itself never got updated but author hard to notice those incidents are happened. For simplicity sake, printing out timestampt each time its updated to check if it's latest or not. Course it does work if it's arbitrary but have to open comment each time.

**Comment by orta** [comment]
Interesting, what about from this:

screen shot 2017-01-15 at 2 21 59 pm

To this:

screen shot 2017-01-15 at 2 22 31 pm

I think what you'd like to see is pretty universal

**Comment by kwonoj** [comment]
Yes, that make sense.

**Comment by deecewan** [comment]
a the risk of beating an old PR, I like that second option a lot.

**Comment by orta** [comment]
I agree, let's ship that - happy to take a fresh PR on that one? could be the two PRs merged

**Comment by kwonoj** [comment]
Yeah, this PR stall too long time as I couldn't give enough attention. Maybe this can be just closed and create new one instead for other way around.

**Comment by orta** [comment]
Works for me 👍 - that's totally understandable

**Pull request closed without merging**
