### PR TITLE
Gitlab: Upgrade @gitbreaker/node from ^21.3.0 to ^35.7.0

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
issue https://github.com/danger/danger-js/issues/1301

I'm trying to update a gitbreaker version, as the switch happen, but the version used is outdated. As latest gitbreaker version has well-defined types. 
Initialy failed, seems like my approach was wrong.

### CODE REVIEW

**Comment by ivankatliarchuk** [comment]
need help here. as not clear how-to

**Comment by glensc** [comment]
Describe what are you trying to do here (in PR body). gitbreaker switch is done via https://github.com/danger/danger-js/pull/1318

**Comment by ivankatliarchuk** [comment]
updated

**Comment by ivankatliarchuk** [comment]
Feel free to create an MR with the fix, and I will close this one np.

**Comment by glensc** [comment]
ok, the PR title is actually about `GitLab: Upgrade @gitbreaker/node from ^21.3.0 to ^35.7.0`

**Comment by glensc** [comment]
also, seems this overlaps https://github.com/danger/danger-js/pull/1355, as those structures are now provided by the gitbreaker package?

**Comment by ivankatliarchuk** [comment]
Most of the structure covered by `gitbreaker`, this is correct.

**Comment by muuvmuuv** [comment]
I get the recommendation to switch to @gitbeaker/rest, maybe consider this instead of just upgrading?

**Comment by orta** [comment]
Looks to me like https://github.com/danger/danger-js/pull/1406 did this

**Pull request closed without merging**
