### PR TITLE
Fix meta on prs

### PR DESCRIPTION
**Pull request by f-meloni**
I've got the changes of the other PR here too by mistake :(, but they are just 2 lines

### CODE REVIEW

**Comment by orta** [comment]
Great, so it was the results transformations - interesting

**Comment by f-meloni** [comment]
But i need to re record one of the snapshots that i forgot :D

**Comment by f-meloni** [comment]
Actually was failing because there was a place where i didn't handle the meta correctly :)

**Comment by orta** [comment]
I dunno why it's still yellow, it's green on travis. Merging.

**Pull request merged**
