### PR TITLE
add support for Docker Cloud CI

### PR DESCRIPTION
**Pull request by camacho**
This add support for the [Docker Cloud CI](https://cloud.docker.com)

### CODE REVIEW

**Comment by orta** [comment]
Awesome - looks good, can you also add this to the README ( where we list all of the current supported CIs ) please also

**Comment by camacho** [comment]
Will do - for the changelog, do you want a full bump to `0.11.0` for this new CI support?

**Comment by orta** [comment]
We tend to do a version bump as a separate PR, but I'm totally fine with this - our deployment stuff is something we're thinking about #117

**Comment by orta** [comment]
Cool, yeah, let's do this, might see about getting the auto-tag deployment set up for 0.11 - so give me a few hours to get it published

**Comment by camacho** [comment]
Awesome, thanks for merging 👍

**Pull request merged**
