### PR TITLE
TypeScript support, + danger.d.ts, + danger DSL change

### PR DESCRIPTION
**Pull request by orta**
Adds support for `dangerfile.ts` and uses the Jest config system to handle transformation.

---

**Previous notes:**

This PR started small, but had a while to do some work on the trainf, so I programmed away.

This provides the initial basic setup for TypeScript. I added a test but it is way slow, 41 seconds. 

So this will fail. The fail does lead to an interesting culprit for why It is slow though: 

screen shot 2017-03-16 at 18 02 01

I think when we load up Babel or TypeScript then every JS file is sent through babel including all `node_modules` - which could definitely slow it down. This is likely something inside the Jest env, that should be pretty easy to track down.

### CODE REVIEW

**Comment by deecewan** [comment]
I'm assuming that this references #169?

**Comment by orta** [comment]
Yeah #169 mainly, I've used up my computer time for today on #174 - but will probably start going over this again in the next few days

**Comment by orta** [comment]
Note to self, [process.execSync](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) can be used to run a child process synchronously. For our Dangerfile.

**Comment by orta** [comment]
Alright, I think this should be good to go from the typescript support side. I'd like reviews around that.

I'd like to continue working on this PR specifically on two things, making Circle CI use a `dangerfile.ts` and adding a Dangerfile rule about ensuring the d.ts in the repo is completely up to date.

**Comment by orta** [comment]
OK, the circle CI dangerfile is 👍 

Fixes #84 

screen shot 2017-03-19 at 09 09 04

**Comment by orta** [comment]
Our current setup makes it possible for the circle ci danger to pass, and to delete the current message on a PR.

This can be fixed by either https://github.com/danger/danger-js/issues/162 or the Danger ID thing discussed in https://github.com/danger/danger-js/issues/166

**Comment by orta** [comment]
green!

**Pull request merged**
