### PR TITLE
Support Bitbucket Server personal repositories

### LINKED ISSUE #1121: [BUG] BitBucketServer personal projects are not taken into consideration
**Describe the bug**
In BitbucketServer you can use project repositories, but you can also create your own personal repositories in your account. These follow a slightly different path structure:

https://bitbucker.server/projects/FOO/repos/BAR/pull-requests/1
https://bitbucker.server/projects/~user/repos/BAR/pull-requests/1

In case danger is invoked for a personal project, the resolved API path is wrong

See docs: https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#personal-repositories

**To Reproduce**
Steps to reproduce the behaviour:
1. run danger pr https://bitbucker.server/projects/FOO/repos/BAR/pull-requests/1
2. danger will get a 404 unable to fetch a correctly resolved API call

**Expected behaviour**
In our case, the bitbucket server host structure has a root path, which can be also relevant to the scenario:
* a PR to this URL: https://bitbucket.server/bitbucket/projects/~USER/repos/BAR/pull-requests/3
* is resolved to: https://bitbucket.server/bitbucket/rest/api/1.0/bitbucket/projects/~USER/repos/BAR/pull-requests/1
* where it should be: https://bitbucket.server/bitbucket/rest/api/1.0/projects/~USER/repos/BAR/pull-requests/1

**Your Environment**
 | software         | version
| ---------------- | -------
| danger.js          | 10.6.3
| node             | 14.16.0
| npm              | 7.5.6
| Operating System | macOS 10.15.7

### PR DESCRIPTION
**Pull request by danibaeyens**
Fixes #1121 

https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#personal-repositories

### CODE REVIEW

**Comment by danibaeyens** [comment]
The way the API works is the same way as for general projects, so there are no changes in that aspect.
I've not added tests for this one because it would be duplicating everything for this optional regex char, but any suggestion about what can be added is welcomed.

**Comment by orta** [comment]
That's fine re: tests - can you add a changelog entry, and we're fine to ignore that travis red 👍🏻

**Comment by danibaeyens** [comment]
I didn't see there was a conflict. Now it's fine again

**Comment by orta** [comment]
Thanks!

**Pull request merged**
