### PR TITLE
Allows fakeci to run via DANGER_TEST_PR and DANGER_TEST_REPO env vars

### PR DESCRIPTION
**Pull request by nsfmc**
This is a pretty good way to test danger and also a lightweight way to
evaluate if "danger is right for you™". Example in README gives a pretty
good overview.

### CODE REVIEW

**Comment by nsfmc** [comment]
i'm not sure how i feel about the env var names or if this behavior should be spun off into its own CI, this felt like the right spot, though. happy to hear any feedback

**Comment by orta** [comment]
This feels good to me for now, ideally this will need moving into a `danger local` command which can fake it all appropriately ( which is how we do it in Ruby ) but I have no problem with this 👍

**Comment by orta** [comment]
I should see what's up with Circle

**Comment by orta** [comment]
Yeah. Let's get this in 👍

**Pull request merged**
