### PR TITLE
Use top-level exports in '.d.ts' instead of a module augmentation.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Addresses issues raised in https://github.com/Microsoft/TypeScript/issues/24267. You probably want to view with whitespace diffing disabled.

### CODE REVIEW

**Comment by orta** [comment]
Thanks! This is a generated interface, so I'll replicate your changes and fix it in this PR

**Comment by DanielRosenwasser** [comment]
Duh, missed that. :sad:

**Comment by orta** [comment]
Thanks!

Merge on green

**Comment by orta** [comment]
Interesting, looks like the checks API means I can't do merge on green because I had a warning give a neutral result - will see what that looks like when CI is done

**Comment by orta** [comment]
screen shot 2018-05-21 at 1 33 43 pm

Followed the instructions and it looks 👍

**Pull request merged**
