### PR TITLE
docs/tutorials: Fix syntax of JSONDiffForFile dump

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by glensc** [comment]
The example has "chalk" in `dependencies.added`, but not in `dependencies.after`. is that a mistake in the example?

**Comment by glensc** [comment]
Also, shouldn't the values of `before` and `after` differ a bit to make it real-life-like? the all versions are the same...

**Review by fbartho — APPROVED** [review]

**Comment by fbartho** [comment]
>The example has "chalk" in dependencies.added, but not in dependencies.after. is that a mistake in the example?

@glensc I haven't extensively used that functionality, so I can't tell you what's expected. I suspect we'd have to actually test the code to see.

**Comment by orta** [comment]
Yeah, looking at this test: https://github.com/danger/danger-js/blob/a6b40e953ff318c6230bf0f09152e4ba58cd567f/source/platforms/github/_tests/_github_git.test.ts#L377-L439

The chalk is a typo, the difference is only meant to be the addition of the new dep so I wouldn't expect the change to be too big

**Pull request merged**
