### PR TITLE
Try fix the CLI

### PR DESCRIPTION
**Pull request by orta**
While work is ongoing in #462 I've done some work to make `danger pr` work, and hopefully undo the damage done in the last two releases #463

### CODE REVIEW

**Comment by orta** [comment]
Also run `danger pr` during the tests, so we know for sure if it's broken

**Comment by orta** [comment]
I've shipped this as `3.0.0.beta.1`

**Comment by paulmelnikow** [comment]
Hey, just a heads up, I'm seeing Danger 3.0 run in CI, invoked using plain `danger`. I'm getting a zero exit status though it really should be a failure since we haven't switched to `danger ci`. Also it seems like there's supposed to be some output warning that the invocation needs to change, though it's not being printed:

https://circleci.com/gh/badges/shields/936?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hawkrives** [comment]
I was noticing the "you may not have switched to danger ci" warning even though I have switched… maybe the condition for printing is flipped? (I should really report these in a more timely fashion, sorry.)

**Pull request merged**
