### PR TITLE
Update Bamboo CI source for compatibility with 7.0 version

### PR DESCRIPTION
**Pull request by nataliSM**
Resolves issue: #1052

### CODE REVIEW

**Comment by orta** [comment]
Any chance you can make it support both, then we don't have to make a breaking change (as I assume anyone can still be using the older versions)?

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a changelog entry for your changes. You can find it in `CHANGELOG.md` 

Please add your change and name to the master section.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b6e2f239aa7f46c98554035456ba4072f87114f6
</p>

**Comment by nataliSM** [comment]
@orta The problem is that I can not find a version for which the previous version is valid. In previous versions, bamboo_inject_prId and bamboo_repository_pr_key keys are not mentioned. First mentioned of bamboo_repository_pr_key in 7.0

**Comment by nataliSM** [comment]
If somehow we could connect @tim3trick (author of this [pr](https://github.com/danger/danger-js/pull/1026)) and find out for which version he implemented the functionality, it would be cool

**Comment by orta** [comment]
Cool yeah - this seems fine, a search on google for the string literally only returns results from inside this repo. Perhaps it came from an older [injected variables](http://saibaldey.blogspot.com/2018/02/how-to-manage-dynamic-variables-in.html) feature I can't find much info for


I'll give Tim some time to reply, but otherwise I think this is OK to not class as a major breaking

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a changelog entry for your changes. You can find it in `CHANGELOG.md` 

Please add your change and name to the master section.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1eea772e5948405ae97ed71ec88ac246335e570a
</p>

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add a changelog entry for your changes. You can find it in `CHANGELOG.md` 

Please add your change and name to the master section.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7cf21f8aceca986d0fb5de265b081bb5b173c6f4
</p>

**Pull request merged**
