### PR TITLE
Fix --base option for danger local cli

### LINKED ISSUE #496: `danger local --base` inconsistency
Doing some more testing with `--base`, looks like it is being ignored on the call to`localGetDiff` triggered in the subprocess:

```
DEBUG="*" ./node_modules/.bin/danger local --base develop
 danger:process_runner Starting sub-process run with  +0ms
 danger:localGetDiff git diff develop...HEAD +0ms
 danger:localGetDiff git log develop...HEAD --pretty=format:'{ "sha": "%H", "parents": "%p", "author": {"name": "%an", "email": "%ae", "date": "%ai" }, "committer": {"name": "%cn", "email": "%ce", "date": "%ci" }, "message": "+0ms"},'
 danger:process_runner Preparing to run: /Users/adam.moss/.nvm/versions/node/v9.4.0/bin/node,/Users/adam.moss/projects/project_name/node_modules/danger/distribution/commands/danger-runner.js,--base,develop +29ms
 danger:runDangerSubprocess Running subprocess: node - /Users/adam.moss/projects/project_name/node_modules/danger/distribution/commands/danger-runner.js,--base,develop +0ms
2018-01-24T14:00:53.419Z danger:runner Started Danger runner with

2018-01-24T14:00:53.426Z danger:runner Got STDIN for Danger Run

2018-01-24T14:00:53.441Z danger:localGetDiff git diff master...HEAD

2018-01-24T14:00:53.455Z danger:localGetDiff git log master...HEAD --pretty=format:'{ "sha": "%H", "parents": "%p", "author": {"name": "%an", "email": "%ae", "date": "%ai" }, "committer": {"name": "%cn", "email": "%ce", "date": "%ci" }, "message": "%s"},'

2018-01-24T14:00:53.469Z danger:runner Evaluating dangerfile.js

2018-01-24T14:00:53.470Z danger:inline_runner Started parsing Dangerfile:  dangerfile.js

2018-01-24T14:00:53.470Z danger:inline_runner Finished running dangerfile:  dangerfile.js

2018-01-24T14:00:53.471Z danger:inline_runner Scheduler waiting on: 0 tasks

2018-01-24T14:00:53.471Z danger:inline_runner Finished scheduled tasks

2018-01-24T14:00:54.424Z danger:runner Process has finished with 0 undefined, sending the results back to the host process

 danger:runDangerSubprocess Got JSON results from STDOUT +1s
 danger:runDangerSubprocess child process exited with code 0 +5ms
 danger:executor Got Results back, current settings { stdoutOnly: true,
 verbose: undefined,
 jsonOnly: false,
 dangerID: 'default' } +0ms
 danger:executor Writing to STDOUT: { fails: [],
 warnings: [],
 messages: [],
 markdowns: [],
 scheduled: [] } +2ms
Danger: Passed review, received no feedback.
```

### PR DESCRIPTION
**Pull request by peterjgrainger**
Fixed #496

### CODE REVIEW

**Comment by peterjgrainger** [comment]
I see the test failing, i'll try to recreate locally

**Comment by peterjgrainger** [comment]
@orta A previous build fails on the same issue, I think this test fails if git log master...HEAD has no history i.e. HEAD === master

Let me know if I need to change anything.  I believe everything is working as it is supposed to.

**Comment by orta** [comment]
Yeah, that's something I've wanted to fix but haven't (been working on https://github.com/danger/peril/issues/159 for the last few weeks straight) I was going to add a check if head === master just exit with 0 and give a log saying "doing nothing"

**Comment by orta** [comment]
Looks 👍 regardless :D

**Pull request merged**
