### PR TITLE
Add tests directory to .npmignore

### LINKED ISSUE #42: Don't ship test files
Probably needs changes in the npmignore

### PR DESCRIPTION
**Pull request by macklinu**
Resolves #42

Checking out the codebase and hoping to get involved, wanted to help resolve a simple open issue in the process. 😺 

## Testing steps

- Run [`npm pack`](https://docs.npmjs.com/cli/pack)
- Open the resulting tarball. At the time of opening this PR, `tar -xf danger-0.6.10.tgz`
- Inspect the `package/` directory (the unzipped tarball) and ensure there are no test files or directories

Running through the steps on master and inspecting the output: 

```
$ find package/ -type d -name "_tests" -print
package//distribution/ci_source/_tests
```

And the result of running through the steps on this branch:

```
$ find package/ -type d -name "_tests" -print
# no results
```

### CODE REVIEW

**Comment by orta** [comment]
yeahhhhhhh - this looks great 💃

Want to add a changelog entry then we're good to go 👍

**Comment by macklinu** [comment]
Oops, I'll amend that commit with my GitHub name 😄

**Comment by orta** [comment]
I know, check out my fancy danger integrations ;)

**Comment by orta** [comment]
rock - thanks, so we conform to the [moya contributors guideline thingy](https://github.com/moya/contributors), which means you get an invite into the org, no pressure

**Pull request merged**
