### PR TITLE
WIP: support standalone local execution

### PR DESCRIPTION
**Pull request by adam-moss**
Working in progress for #308 ... adding so you can see if this is going along the right track.

I did initially create a `local` command but it seems if no env vars are specified it defaults to it anyway with the `run` method, so I took it back out.

Comments/modifications appreciated.

### CODE REVIEW

**Comment by orta** [comment]
This definitely is the right way to get started 👍 

I think I'd rather have a specific command for doing this, the version without env vars is really so you can fake your CI and still work against GitHub/GitLab, this aims to work without that completely.

**Comment by adam-moss** [comment]
Ok, I've added the `local` command back in a removed `LocalRepo` as a valid CI source so `run` can't use it.

Now I just need to work out why it is dying with a "can't find package.json" when executing the dangerfile.  I presume this is because I haven't actually populated any of the arrays yet...

**Comment by orta** [comment]
I think the package.json issue is https://github.com/danger/danger-js/issues/261 - which has a quick fix workaround

**Comment by adam-moss** [comment]
Yeah, it is 🤦‍♂️

**Comment by zdenektopic** [comment]
Is there any progress on this? I would really appreciate this as we are using Bitbucket, but is easier for us to use our own method of passing the markdown results to PR.

**Comment by orta** [comment]
@zdenektopic you should build out bitbucket support for DangerJS, we have it in Danger Ruby - this PR doesn't really affect that

**Comment by zdenektopic** [comment]
@orta I am aware. But I don't really need bitbucket support as I don't need any info basically. Just to be able to compare 2 branches and work with that. And then get markdown table with results which I can store to file or export to env temporarily and then read from when composing comment response from CI.

**Comment by adam-moss** [comment]
Been on vacation so haven't done much with this, will look again at some point this week.

**Comment by zdenektopic** [comment]
Cool, because I would really appreciate it! :)

**Comment by orta** [comment]
Thanks @adam-moss - I've taken your work and mostly wrapped it up today, see #473

**Pull request closed without merging**
