### PR TITLE
Check windows support

### PR DESCRIPTION
**Pull request by orta**
This runs the formatter on `source/runner/_tests/_danger_runner.test.ts` as well as undoing the Windows check for the danger eval tests.

### CODE REVIEW

**Comment by macklinu** [comment]
Is this related to #224?

**Comment by orta** [comment]
Yes, I know that updating Jest broke our windows support (something about the haste map generation) and so maybe updating it one more time would fix it - it didn't, now it requires more digging 👍

**Comment by tivac** [comment]
I'm not really able to dig into this too much more, but I'm happy to help QA it once you think you've got a fix.

It's something, hopefully. 🤔

**Comment by orta** [comment]
Aye, right now my plan is to try understand what options go into the map when jest does it, vs when Danger does

**Comment by macklinu** [comment]
I'm not familiar with the inner workings of Jest, but I was poking around the Jest codebase to see how they create a runtime vs. how Danger does it. I came across [these lines](https://github.com/facebook/jest/blob/9b157c3a7c325c3971b2aabbe4c8ab4ce0b0c56d/packages/jest-runtime/src/cli/index.js#L66-L82) in the `jest.run()` function, which is a different way to create a runtime environment than what [we are currently doing](https://github.com/danger/danger-js/blob/0.19.0/source/runner/DangerfileRunner.ts#L18-L44) in the `DangerfileRunner.ts` file.

To translate what happens in `jest.run()` to `DangerfileRunner.ts`, I think it would look like this:

```diff
diff --git a/source/runner/DangerfileRunner.ts b/source/runner/DangerfileRunner.ts
index a4467e8..c8985fe 100644
--- a/source/runner/DangerfileRunner.ts
+++ b/source/runner/DangerfileRunner.ts
@@ -31,10 +31,10 @@ export async function createDangerfileRuntimeEnvironment(dangerfileContext: Dang
   }
 
   // Setup a runtime environment
-  const hasteConfig = { automock: false, maxWorkers: 1, resetCache: false }
-  const hasteMap = await Runtime.createHasteMap(config, hasteConfig).build()
-  const resolver = Runtime.createResolver(config, hasteMap.moduleMap)
-  const runtime = new Runtime(config, environment, resolver)
+  const hasteMap = await Runtime.createContext(config, {
+    maxWorkers: os.cpus().length - 1,
+  })
+  const runtime = new Runtime(config, environment, hasteMap.resolver)
 
   return {
     context,
```

I tried this out locally on my Macbook, and the tests pass, but I'm not sure what the ramifications would be for Danger or if it would help with fixing #224.

I don't have a Windows machine to test on, but I'm glad to help with this however else I can. 👍

**Comment by orta** [comment]
I don't have a windows machine, but the appveyor tests have been enough to ensure that it continues working - but that doesn't seem to have been enough alas

**Comment by orta** [comment]
Deprecated by https://github.com/danger/danger-js/issues/273

**Pull request closed without merging**
