### PR TITLE
Add linesOfCode in GitDSL

### PR DESCRIPTION
**Pull request by ninjaprox**
Address #545.

### CODE REVIEW

**Comment by orta** [comment]
Interesting, cool! 

I think this is is going to need docs stating that this way more of an expensive call than someone would think. For example, you're asking the GitHub API for the diff of every file individually - which could quickly blow through the 5k per hour limit on large PRs

**Comment by ninjaprox** [comment]
Make sense. It actually can be improved with one API call per PR for the diffs of all files. `BitBucketServerGit` also needs update to support this. I'll update the PR soon.

**Comment by ninjaprox** [comment]
I made an update to memoize the diff result so that it won't deplete the 5k per hour limit. `BitBucketServerAPI` seems not to work anymore due to the API v1 deprecation, and not sure if any Bitbucket users out there, so I leave `BitBucketServerGit` as-is. We can update it later along with Bitbucket API v2. In v2, [/2.0/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/diff](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/diff) returns a plain text diff which can help remove `getStructuredDiffForFile` in `GitJSONToGitDSLConfig`, and unify usage of `getFullDiff` for both GitHub and BitBucket.

**Comment by orta** [comment]
Yeah, this makes sense - thanks 👍 cool

**Pull request merged**
