### PR TITLE
CI: Split integration tests to own workflow

### PR DESCRIPTION
**Pull request by glensc**
Split CI file to be able override it with node 16.
Alternative fix to https://github.com/danger/danger-js/pull/1393

`create-react-app` doesn't allow running other versions than latest, and latest 5.0.1 requires node 16:
- https://github.com/danger/danger-js/pull/1393#issuecomment-1657196122

### CODE REVIEW

**Comment by glensc** [comment]
@fbartho @orta this is to fix CI. See also the other solution:
- https://github.com/danger/danger-js/pull/1393

Merge which one suits you more.

**Comment by orta** [comment]
Opted to go with #1393 - thanks!

**Comment by glensc** [comment]
825d797dd02ee712d4d1c3b76e1e0eb41e5eb83d should be cherry-picked to some other branch

**Comment by glensc** [comment]
Cherry-picked into a fresh pr:
- https://github.com/danger/danger-js/pull/1509

**Pull request closed without merging**
