### PR TITLE
Fix for #496

### PR DESCRIPTION
**Pull request by peterjgrainger**
Fix for the --base flag discussed in #496

### CODE REVIEW

**Comment by orta** [comment]
The history on this PR is a little confusing, did you edit some of the commits on master?

**Comment by orta** [comment]
And please don't add a `package-lock.json` - we should get that in the `.gitignore`

**Comment by peterjgrainger** [comment]
@orta I squashed the commits I made.  Did I overwrite something?  I'll check.

no problem on the package-lock.  I forgot you are using yarn.  I'll delete it.  Can put in the ignore file, stop other people making the same mistake.

Is the rest of the change OK?

**Comment by orta** [comment]
It's a little hard to see where the changes are, given the amount of LOC in the PR

**Comment by peterjgrainger** [comment]
Ok.  Np.  I'll update and ask again

**Pull request closed without merging**
