### PR TITLE
Resolve node-fetch@^2.3.0 to 2.6.7 to fix security vulnerability GHSA-r683-j2x4-v87g

### PR DESCRIPTION
**Pull request by jonny133**
Resolve `node-fetch@^2.3.0` to `2.6.7` to fix https://github.com/advisories/GHSA-r683-j2x4-v87g

Removed from `package.json` as it did not prevent `node-fetch@^2.3.0` resolving `2.3.0` and is not necessary now.

Update the types to latest 2.x as well

### CODE REVIEW

**Comment by unfernandito** [comment]
Hello @orta 

Coul be merged this PR and launch a new release?

Thanks.

**Comment by orta** [comment]
Yep 👍🏻

**Comment by orta** [comment]
This PR _removes_ node-fetch from the deps, given that we use it - that does not seem like the right answer

**Comment by orta** [comment]
Strange, it did merge but the PR is still open, so I'll manually close

**Comment by orta** [comment]
OK, that's shipped in 10.9.0

**Pull request closed without merging**
