### PR TITLE
fix codeship - actually return the json from api.getPullRequests

### PR DESCRIPTION
**Pull request by caffodian**
#120 

This PR may not be quite ready, for several reasons, but help is welcome:

Firstly, I'm not sure if there's any nice way to test this.  This code doesn't look used outside of Codeship.  Due to the issues below, I'm also unable to build danger-js. :/  

I'm not a typescript user in my day to day. Doing a straight up "yarn install", the pre-commit and prepush hooks are both broken in different ways. For some reason, prettier never actually finishes running in the pre-commit, even though this change is just to 1 file. 

The prepush hook  to `yarn run build` fails with the following:

```
yarn run v0.27.5
$ shx rm -rf ./distribution && tsc -p tsconfig.production.json && madge ./distribution --circular

503     interface Mock<T = {}> extends Function, MockInstance<T> {
                         ~

node_modules/@types/jest/index.d.ts(503,22): error TS1005: ',' expected.


503     interface Mock<T = {}> extends Function, MockInstance<T> {
                           ~

node_modules/@types/jest/index.d.ts(503,24): error TS1005: '>' expected.


503     interface Mock<T = {}> extends Function, MockInstance<T> {
                             ~

node_modules/@types/jest/index.d.ts(503,26): error TS1109: Expression expected.


503     interface Mock<T = {}> extends Function, MockInstance<T> {
                               ~~~~~~~

node_modules/@types/jest/index.d.ts(503,28): error TS1109: Expression expected.


505         (...args: any[]): any;
            ~

node_modules/@types/jest/index.d.ts(505,9): error TS1005: ',' expected.


505         (...args: any[]): any;
                    ~

node_modules/@types/jest/index.d.ts(505,17): error TS1005: ',' expected.


505         (...args: any[]): any;
                            ~

node_modules/@types/jest/index.d.ts(505,25): error TS1005: ';' expected.


508     interface SpyInstance<T = {}> extends MockInstance<T> {
                                ~

node_modules/@types/jest/index.d.ts(508,29): error TS1005: ',' expected.


508     interface SpyInstance<T = {}> extends MockInstance<T> {
                                  ~

node_modules/@types/jest/index.d.ts(508,31): error TS1005: '>' expected.


508     interface SpyInstance<T = {}> extends MockInstance<T> {
                                    ~

node_modules/@types/jest/index.d.ts(508,33): error TS1109: Expression expected.


508     interface SpyInstance<T = {}> extends MockInstance<T> {
                                      ~~~~~~~

node_modules/@types/jest/index.d.ts(508,35): error TS1109: Expression expected.


541 }
    ~

node_modules/@types/jest/index.d.ts(541,1): error TS1128: Declaration or statement expected.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've attempted to bump the @types/jest version, but doesn't fix it. Typescript looks up to date too.

### CODE REVIEW

**Comment by orta** [comment]
Interesting, your Travis also fails like #450 - I'll take a look over the changes in master and get that green 

And will see about your TS errors - I've been seeing the same ones on danger.systems too

**Comment by orta** [comment]
Otherwise this definitely looks good, I agree on your outcome

**Comment by orta** [comment]
OK, I've merged this in via #453 - thanks for the PR, I _should_ have a release out today

**Comment by caffodian** [comment]
Thanks!

**Pull request merged**
