### PR TITLE
Adds more logging to handleResultsPostingToPlatform

### PR DESCRIPTION
**Pull request by ashfurrow**
This is additional logging to help diagnose https://github.com/ashfurrow/peril-settings/issues/8

### CODE REVIEW

**Comment by orta** [comment]
merge on green

**Comment by ashfurrow** [comment]
@orta when you have a minute, could you release danger-js with this change? Thanks!

**Comment by orta** [comment]
already did it, and updated peril

**Comment by ashfurrow** [comment]
Ah, thanks. I was looking at https://github.com/danger/danger-js/releases and not seeing it. Thanks!

**Pull request merged**
