### PR TITLE
Fix: [Github] Multiple Inline Comments on the same file/line should all be posted

### PR DESCRIPTION
**Pull request by Rouby**
This PR should address #1134 by sending all inline comments as a review combined.

### CODE REVIEW

**Comment by orta** [comment]
Structurally this looks good 👍🏻  - I'd like a test or two though because I don't want this breaking from other contributors changes in the future

**Comment by Rouby** [comment]
> a test or two
Will do :)

**Review by fbartho — APPROVED** [review]
This PR looks good to me! Just need to add an entry to the Changelog!

Something like the following inside "Your comment below here":

```markdown
- Fix: [Github] Multiple Inline Comments on the same file/line should all be posted [#1176](https://github.com/danger/danger-js/pull/1176) [@Rouby]
```

**Comment by Rouby** [comment]
> This PR looks good to me! Just need to add an entry to the Changelog!
> 
> Something like the following inside "Your comment below here":
> 
> ```gfm
> - Fix: [Github] Multiple Inline Comments on the same file/line should all be posted [#1176](https://github.com/danger/danger-js/pull/1176) [@Rouby]
> ```

Thanks and done 👍

**Comment by fbartho** [comment]
Note: CI is blocked by #1189 or an alternative solution there (so don’t be alarmed by the test failure)

**Comment by f-meloni** [comment]
Would make sense to have the new comment logic enabled when there is a specific flag (e.g.,` --use-github-reviews`) or something like that, so that is disabled by default and we can then investigate it with calm (but Danger keeps working as expected in the meantime)?

**Comment by orta** [comment]
Yeah, perhaps I misinterpreted this PR, IMO warnings/fails/etc which cannot be registered in the diff should show up in the main comment. I personally find reviews annoying in PRs (because they don't get overwritten by the edits and thus spam the PR on every CI run )

I think this behavior as is could be a flag but we should get it aligned with how danger ruby does is which is ^

**Comment by f-meloni** [comment]
Yeah, mine was more a temporary suggestion.
Failed tests or lint issues might be affected by this change, so I thought we could keep those working while this gets solved

**Comment by f-meloni** [comment]
PS. I just realised I posted this in the PR and not in the issue 😅 sorry

**Pull request merged**
