### PR TITLE
Azure Devops support

### PR DESCRIPTION
**Pull request by jonasbark**
Follow up based on discussion in: https://github.com/danger/danger-js/pull/1006#discussion_r392591146
This PR now only contains the changes needed to support Azure Devops.

### CODE REVIEW

**Comment by orta** [comment]
Any idea why CI is failing with these changes?

**Comment by jonasbark** [comment]
> Any idea why CI is failing with these changes?

I honestly wish I would have an idea.

**Comment by rajzik** [comment]
@jonasbark Is there any progress on this PR?

**Comment by christoff-1992** [comment]
Just wondering if this is still in scope to be looked at @jonasbark? I would love to use Danger with ADO. 🤞

**Comment by krishnasaga** [comment]
I managed to write a function to use Azure DevOps REST API to get the diff between two branches

```javascript
export const getDiff = async ({
  repository,
  baseVersion,
  targetVersion,
  authKey,
}) => {
  const result = await fetch(
    `${AZURE_ORGANIZATION_URL}/_apis/git/repositories/${repository}/diffs/commits?baseVersion=${baseVersion}&targetVersion=${targetVersion}&api-version=7.1-preview.1`,
    {
      method: 'GET',
      headers: {
        Authorization: `Basic ${authKey} `,
      },
    }
  );

  const json = await result.json();

  return json;
};

```

**Comment by krishnasaga** [comment]
Where can I check the CI log

**Pull request closed without merging**
