### PR TITLE
Fix previousComments error

### LINKED ISSUE #577: Peril Error: `TypeError: previousComments.filter is not a function`
This error is happening in peril against this dangerfile: https://github.com/TokenTax/peril/blob/master/dangerfiles/issues.ts

The error is potentially coming from this line
https://github.com/danger/danger-js/blob/67ed2ba5e7dedf52f502393f50bfc21901ff8943/source/runner/Executor.ts#L298

```
2018-04-27T13:28:33.040322+00:00 app[web.1]: Unable to evaluate the Dangerfile
2018-04-27T13:28:33.043195+00:00 app[web.1]: info: [runner] - Commenting, with results:
2018-04-27T13:28:33.043198+00:00 app[web.1]: mds: 1
2018-04-27T13:28:33.043200+00:00 app[web.1]: messages: 0
2018-04-27T13:28:33.043201+00:00 app[web.1]: warns: 0
2018-04-27T13:28:33.043203+00:00 app[web.1]: fails: 1
2018-04-27T13:28:33.043205+00:00 app[web.1]:
2018-04-27T13:28:33.049339+00:00 app[web.1]: Failing the build, there is 1 fail.
2018-04-27T13:28:33.058095+00:00 app[web.1]: error: Error:  TypeError: previousComments.filter is not a function
2018-04-27T13:28:33.058099+00:00 app[web.1]:     at Executor.sendInlineComments (/app/node_modules/danger/distribution/runner/Executor.js:365:47)
2018-04-27T13:28:33.058101+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:305:51)
2018-04-27T13:28:33.058103+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-04-27T13:28:33.058104+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-04-27T13:28:33.058106+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-04-27T13:28:33.058108+00:00 app[web.1]:     at <anonymous>
2018-04-27T13:28:33.058110+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-04-27T13:28:33.058556+00:00 app[web.1]: /app/out/peril.js:24
2018-04-27T13:28:33.058559+00:00 app[web.1]:         throw reason;```

### LINKED ISSUE #584: previousComments.filter is not a function
This happens for us on any run that targets a new issue just being opened: (for example https://github.com/withspectrum/spectrum/issues/2994)

```
2018-05-02T14:09:36.626079+00:00 app[web.1]: info: ## issues.edited on unknown
2018-05-02T14:09:36.626216+00:00 app[web.1]: info:    1 runs needed: dangerfile.issues.ts
2018-05-02T14:09:38.029297+00:00 heroku[router]: at=info method=POST path="/webhook" host=peril-spectrum.herokuapp.com request_id=1dcc82ff-cf35-4f51-bcb3-e1554f08ee4c fwd="192.30.252.36" dyno=web.1 connect=3ms service=1443ms status=200 bytes=1886 protocol=https
2018-05-02T14:09:38.014458+00:00 app[web.1]: Unable to evaluate the Dangerfile
2018-05-02T14:09:38.019091+00:00 app[web.1]: info: [runner] - Commenting, with results: 
2018-05-02T14:09:38.019095+00:00 app[web.1]: mds: 1
2018-05-02T14:09:38.019096+00:00 app[web.1]: messages: 0
2018-05-02T14:09:38.019098+00:00 app[web.1]: warns: 0
2018-05-02T14:09:38.019100+00:00 app[web.1]: fails: 1
2018-05-02T14:09:38.019102+00:00 app[web.1]:   
2018-05-02T14:09:38.022778+00:00 app[web.1]: Failing the build, there is 1 fail.
2018-05-02T14:09:38.034880+00:00 app[web.1]: error: Error:  TypeError: previousComments.filter is not a function
2018-05-02T14:09:38.034890+00:00 app[web.1]:     at Executor.sendInlineComments (/app/node_modules/danger/distribution/runner/Executor.js:365:47)
2018-05-02T14:09:38.034893+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:305:51)
2018-05-02T14:09:38.034894+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-05-02T14:09:38.034896+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-05-02T14:09:38.034897+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-05-02T14:09:38.034899+00:00 app[web.1]:     at <anonymous>
2018-05-02T14:09:38.034901+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-05-02T14:09:38.035229+00:00 app[web.1]: /app/out/peril.js:24
2018-05-02T14:09:38.035232+00:00 app[web.1]:         throw reason;
2018-05-02T14:09:38.035233+00:00 app[web.1]:         ^
2018-05-02T14:09:38.035235+00:00 app[web.1]: 
2018-05-02T14:09:38.035239+00:00 app[web.1]: TypeError: previousComments.filter is not a function
2018-05-02T14:09:38.035241+00:00 app[web.1]:     at Executor.sendInlineComments (/app/node_modules/danger/distribution/runner/Executor.js:365:47)
2018-05-02T14:09:38.035242+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:305:51)
2018-05-02T14:09:38.035259+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-05-02T14:09:38.035261+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-05-02T14:09:38.035262+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-05-02T14:09:38.035264+00:00 app[web.1]:     at <anonymous>
2018-05-02T14:09:38.035266+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
```

Here's our Dangerfile: https://github.com/withspectrum/peril-settings/blob/master/dangerfile.issues.ts It was working perfectly fine until I pushed the latest update, so I think this is a regression?

### PR DESCRIPTION
**Pull request by mxstbr**
Closes #577

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this makes sense 👍

**Comment by sunshinejr** [comment]
This should indeed solve the issue, but I'm wondering why Peril went to `sendInlineComments` for making an issue comment anyways. Might be worth taking a look.

**Comment by orta** [comment]
It's the same messaging process as a PR in general, just trying to avoid forking the code inside danger-js for Peril's sake

**Comment by sunshinejr** [comment]
Yeah, I was just thinking if there could be a way of checking if this is a PR or Issue to avoid going through all the `inlineComments` phase.

**Pull request merged**
