### PR TITLE
Allow access to the issue behind a PR

### LINKED ISSUE #154: Allow access to the issue behind a PR
Every Github PR has an issue behind it, and the issues contains the reference to the labels.  This is useful to enforce a label being used on each PR.

[Github Issues Docs](https://developer.github.com/v3/issues/)
[Current Github DSL](https://github.com/danger/danger-js/blob/master/source/dsl/GitHubDSL.ts)

Proposal: Add `danger.github.issue` that contains a reference to the issue behind this PR.

### PR DESCRIPTION
**Pull request by deecewan**
Now, users can access `danger.github.issue` to check if labels are applied, etc.

There is not much in an issue that isn't in a PR, so at the moment all the is under `issue` is `labels`.

This has expanded a little and also adds reviews and requested reviews, so users can make sure there is at least x reviewers requested/made

Closes #154

### CODE REVIEW

**Comment by orta** [comment]
Sorry, I'm my honeymoon - so it's taking a while to get around to looking at all these PRs - but my wife is asleep, and I got some time, so I'll clone this and see if I can grok what's up with the tests

**Comment by deecewan** [comment]
no rush. enjoy yourself :)

**Comment by orta** [comment]
cool, looks like these functions need to be mocked out in some existing tests, and ideally adding some to cover the API calls, will add them

**Comment by macklinu** [comment]
@orta I'm returning from a five-week hiatus, so I'll look to get involved in open issues and PRs over the course of this work week. Hope you have a great honeymoon!

**Comment by orta** [comment]
Rock - @deecewan I sent you a PR to your branch (you might not be watching your own repo) with a bunch of fixes here 👍

**Comment by deecewan** [comment]
you're something special @orta.

**Comment by orta** [comment]
OK, this is good to go

**Comment by orta** [comment]
👍 you're welcome @deecewan

**Pull request merged**
