### PR TITLE
Creates inline docs for all providers (help requested)

### PR DESCRIPTION
**Pull request by orta**
Sorry to ask specifically, but there are some CI provides I have never used on this list, so:

- @benkraus - can you confirm that the BuddyBuild docs look 👍? 
- @deecewan - can you confirm the CodeShip one?
- @camacho - can you confirm the DockerCloud?

This will mean that they show up on the getting started guide:

screen shot 2017-06-26 at 22 04 09
http://danger.systems/js/guides/getting_started.html

### CODE REVIEW

**Comment by macklinu** [comment]
Cleaned up the spacing in the Jenkins docs and updated the URLs to point to jenkins.io.

**Comment by deecewan** [comment]
Updated the docs to include information about codeship classic (which is being phased out, but is still very much in use)

**Comment by orta** [comment]
Thanks everyone, will poke someone about buddy build later

**Comment by benkraus** [comment]
@orta I'll check up on the buddy build stuff, gimme a couple hours.

**Comment by benkraus** [comment]
I took a look, and the directions for BuddyBuild have changed just a bit. I'll open a PR to have them updated. Gimme 'til next week though - I'm away for some family stuff until next Wednesday.

**Comment by orta** [comment]
👍

**Pull request merged**
