### PR TITLE
Adds support for circle ci

### PR DESCRIPTION
**Pull request by nsfmc**
Adds in support for detecting a circle ci environment. this is running side-by-side here https://github.com/nsfmc/danger-js/pull/1 (apologies for any noise)

### CODE REVIEW

**Comment by nsfmc** [comment]
full disclosure, i have not tried this yet under circle, but wanted to open the pr early just in case i was missing something

**Comment by nsfmc** [comment]
this regressing danger test is intentional and tracked on my own branch to confirm that circle is doing the right thing

**Comment by nsfmc** [comment]
i have a followup to this pr at https://github.com/nsfmc/danger-js/pull/2 which gets flow linting correctly on circle (the ignore flag isn't working on flow 0.32.0 on circle at least)

**Comment by orta** [comment]
yeahhhhhh

**Comment by orta** [comment]
this all looks super awesommme

**Comment by orta** [comment]
OK, I've turned Circle on for this repo - looks all perfect to me 👍

**Comment by orta** [comment]
Would you like to join the org @nsfmc - we invite anyone who has sent a PR?

**Comment by orta** [comment]
Yeah, the Flow 0.35 one looks like a 10/10 PR too - that was on my TODO list once I wrap up an artsy project

**Comment by nsfmc** [comment]
@orta yeah would love to be added, not sure what the extent of my contributions will be, for now just integrating with our project repo at work and trying to achieve stability.

**Comment by orta** [comment]
No pressure or expectations to work on the project,t it just gives you the ability to be a bit more in control of your destiny if you need it 👍

**Pull request merged**
