### PR TITLE
Use new env variable to replace old

### PR DESCRIPTION
**Pull request by Soyn**
Bitbucket cloud already has the env variable we want. I have test this by my account.
More info in https://confluence.atlassian.com/bitbucket/variables-in-pipelines-794502608.html

### CODE REVIEW

**Comment by orta** [comment]
Looks good - Can you make it support both and add a changelog please? I'm wary of people using an older build of bitbucket getting fails

**Comment by Soyn** [comment]
Updated!

**Comment by orta** [comment]
Thanks @Soyn  - can you also make it still support the old style, and use the new version if it's there so that we keep backwards compatibility too please

**Comment by Soyn** [comment]
It's a necessary work to support old style? The new bb pipeline env should work if you use pipeline on bb cloud.

**Comment by orta** [comment]
I don't know because I don't use it - so I'd rather err on the side of caution, especially with enterprise-y stuff where anyone could have old versions

**Comment by Soyn** [comment]
I use the bb cloud in my work. The new env variable works well. Maybe we do not need to keep the old style.

**Comment by HelloCore** [comment]
It works on my project too.

**Comment by orta** [comment]
I prefer that we do, I'd rather never break backwards compatibility when it's cheap - it's a single ternary.

**Comment by Soyn** [comment]
Okay! I will update the code to keep the backwards compatibility.

**Comment by orta** [comment]
Thanks! Merge on green

**Pull request merged**
