### PR TITLE
emit console error if `DANGER_GITHUB_API_TOKEN` is not set.

### PR DESCRIPTION
**Pull request by nsfmc**
Without this, danger will appear to fail because it is unable to
execute `.find()` within the PR's comments, this at least 
explains the root cause.

### CODE REVIEW

**Comment by nsfmc** [comment]
i'm curious whether you think this should `throw` the error and stop `danger` before it can continue any further.

**Comment by orta** [comment]
IMO,  throw - can't do anything

**Comment by orta** [comment]
Writing tests is so dreamy with my new VS Code setup 💟 

screen shot 2016-11-28 at 11 13 55

OK - this looks obvious to me what the problem is, let's get this in

screen shot 2016-11-28 at 11 17 47

**Comment by orta** [comment]
Alright - we're green

**Comment by nsfmc** [comment]
rad, sorry for the late replies here, had a pretty busy weekend.

**Pull request merged**
