### PR TITLE
fix of some grammar and typos

### PR DESCRIPTION
**Pull request by NotMoni**

### CODE REVIEW

**Comment by orta** [comment]
Is this automated? I'm not sure I agree with about half of these

**Comment by NotMoni** [comment]
@orta Its not automated. What is the issue?

**Comment by NotMoni** [comment]
@orta why was this close without a reason ?

**Comment by orta** [comment]
Good question, that certainly wasn't me - that app isn't installed on the org, nor have I ever given it access.... Weird!

I can't even re-open

**Comment by orta** [comment]
It looks like you might have pushed my master to your master and completely made the PR empty?

**Comment by NotMoni** [comment]
Oh nooo. Hopefully, the changes are in my local machine.

**Comment by NotMoni** [comment]
I will submit another PR.

**Comment by NotMoni** [comment]
@orta Take a look at this PR- https://github.com/danger/danger-js/pull/1025

:D

**Pull request closed without merging**
