### PR TITLE
Update documentation to clarify use with jenkins and bitbucketserver

### PR DESCRIPTION
**Pull request by HannesT117**

### CODE REVIEW

**Comment by sunshinejr** [comment]
Thanks for PR @HannesT117! Sorry but I didn't use these so I'm not an expert - could you please clarify if these two are necessary for `BitbucketServer` specifically? From the [search](https://github.com/danger/danger-js/search?utf8=✓&q=ghprbGhRepository&type=) it seems like they are used for Jenkins purposes only, but I might be missing something. Thanks!

**Comment by HannesT117** [comment]
Hi @sunshinejr , sorry for not adding a description in the first place! Your totally right anyways, sorry! After playing around with my config I seem to have mixed up everything. I updated my PR to add this information to Jenkins.ts.

**Comment by orta** [comment]
👍

**Comment by sunshinejr** [comment]
No worries @HannesT117, it’s all good. Thank you so much for being a nice citizen and helping others after you’ve figured it out! 👏🏻

**Pull request merged**
