### PR TITLE
fix: mark `body` as nullable for Github PRs

### LINKED ISSUE #1185: [BUG] Body can apparently be null
**Describe the bug**

I'm still looking into this myself, but it looks like `body` can be `null` at least for github PRs?

https://github.com/jest-community/eslint-plugin-jest/pull/1001

**To Reproduce**
1. Create a pull request with no body

**Expected behavior**

It to not error, since the types don't mark `body` as being nullable.

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 10.7.1
| node             | unsure
| npm              | unsure
| Operating System | `ubuntu-latest`

**Additional context**

https://github.com/jest-community/eslint-plugin-jest/blob/main/.github/workflows/lint.yml#L16-L23

### PR DESCRIPTION
**Pull request by G-Rath**
Resolves #1185

### CODE REVIEW

**Comment by G-Rath** [comment]
Looks like CI has failed due to unrelated reasons:

image

**Comment by fbartho** [comment]
This is blocked by #1189 or an alternative solution to the problem!

**Comment by orta** [comment]
I'm also not sure it's something I want to merge on reflection, I think this is a purposeful choice to make life easier for writing dangerfiles

**Comment by G-Rath** [comment]
@orta personally I think if it's possible Danger should normalise this so that it's always a string.

**Comment by orta** [comment]
Good point, just shipped #1191  while waiting on CI 👍🏻 

Thanks for getting this moving @G-Rath

**Pull request closed without merging**
