### PR TITLE
Add support for `danger pr --repl`

### LINKED ISSUE #21: Support opening danger PR into a REPL
This provides an easy way to understand what's going on

### PR DESCRIPTION
**Pull request by macklinu**
Resolves #21

With the new `--repl` flag

image

Previous behavior remains unchanged (logs `jsome(results)`)

image

### CODE REVIEW

**Comment by orta** [comment]
I swear I was talking to someone about this yesterday! Amaze 🍡

**Comment by orta** [comment]
Oh yeah, #21  - I wonder if I carried on that conversation in my head too

**Comment by orta** [comment]
Looks great :D

**Comment by macklinu** [comment]
I was honestly surprised how straightforward this was. It didn't take that much code to inspect `danger` and `results` in a REPL! 💯 😄

**Pull request merged**
