### PR TITLE
Add ability to use GitlabApi by oauth token

### PR DESCRIPTION
**Pull request by Crazymax11**
At my current project we don't have GitLab access token at CI, but instead we have oauth token. So I added a support of OAuth token usage for GitLab

### CODE REVIEW

**Review by orta — APPROVED** [review]
Cool, yeah, this seems reasonable to me

**Comment by Crazymax11** [comment]
@orta sorry for commenting in closed PR, but I see release 10.6.5 at Github interface and don't see it at npm. Is it ok or something broken at project CI?

**Comment by HonzaMac** [comment]
Do we need adjust tests?

**Comment by orta** [comment]
Travis CI had stopped running so this (a a few other PRs) _felt_ green, but wasn't and that was breaking the deploy pipeline. Fixed it up this morning and shipped a new build.

**Pull request merged**
